import { Project, ServiceItem, ProcessStep, PricingPlan, PricingAddOn, WhyUsReason } from './types';

export const SERVICES_DATA: ServiceItem[] = [
  {
    number: '01',
    title: 'Frontend Development',
    description: 'Modern responsive interfaces engineered for lightning performance, fluid interactions, and conversion across all devices.',
    iconName: 'Layout',
    highlights: [
      'Modern responsive interfaces',
      'Interactive UI & advanced animations',
      'Mobile / tablet / desktop optimization',
      'Performance-focused implementation',
    ],
  },
  {
    number: '02',
    title: 'Backend Development',
    description: 'Robust server architectures, scalable databases, and secure APIs engineered to power critical business operations.',
    iconName: 'Cpu',
    highlights: [
      'Database integration & modeling',
      'Secure user authentication',
      'Custom APIs & microservices',
      'Form processing & business logic',
    ],
  },
  {
    number: '03',
    title: 'Full-Stack Development',
    description: 'End-to-end digital solutions uniting modern client interfaces with resilient backend logic, dashboards, and automated pipelines.',
    iconName: 'Layers',
    highlights: [
      'Complete frontend + backend systems',
      'Admin dashboards & client portals',
      'Database architecture & APIs',
      'Custom web applications & workflows',
    ],
  },
  {
    number: '04',
    title: 'Business Websites',
    description: 'High-conversion company, corporate, and service-based websites built to establish authority and generate qualified business leads.',
    iconName: 'Globe',
    highlights: [
      'Corporate & company websites',
      'Service business & lead-gen sites',
      'High-converting landing pages',
      'SEO & analytics pre-configured',
    ],
  },
  {
    number: '05',
    title: 'Custom Web Applications',
    description: 'Tailored digital products, SaaS tools, and workflow systems designed around your exact business mechanics.',
    iconName: 'Zap',
    highlights: [
      'Booking & scheduling systems',
      'Client portals & custom CMS',
      'Internal business management tools',
      'Database-driven dynamic applications',
    ],
  },
  {
    number: '06',
    title: 'Maintenance & Support',
    description: 'Dedicated technical oversight, security updates, and performance optimizations keeping your digital platforms reliable 24/7.',
    iconName: 'ShieldCheck',
    highlights: [
      'Scheduled updates & bug fixes',
      'Speed & Core Web Vitals monitoring',
      'Feature expansions & iterations',
      'Direct priority technical support',
    ],
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'atelier-aura',
    slug: 'atelier-aura',
    title: 'Atelier Aura',
    category: 'Salon / Beauty & Wellness',
    shortDescription: 'An editorial, luxury digital experience crafted for a modern salon and wellness retreat, featuring fluid typography, immersive service menus, and frictionless appointment booking.',
    thumbnail: '',
    image: '',
    liveUrl: 'https://atelier-aura.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 1,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
    caseStudy: {
      overview: 'Atelier Aura is a boutique beauty sanctuary offering curated hair artistry, skin therapy, and holistic wellness treatments. The digital platform was designed from the ground up to reflect the calm, tactile serenity of physical salon environments while serving as an efficient client acquisition and consultation hub.',
      businessType: 'Boutique Hair Salon, Aesthetic Studio & Wellness Sanctuary',
      challenge: 'Traditional salon websites frequently suffer from cluttered third-party booking widgets, dated visual hierarchies, and uninspired layouts that compromise boutique prestige. Atelier Aura needed a digital presence that balanced high-fashion editorial aesthetics with practical booking pathways and transparent service details.',
      designApproach: 'Formulated a serene architectural aesthetic centered around generous negative space, warm neutral undertones, and refined typography. The visual hierarchy invites unhurried exploration while clearly delineating treatment packages, duration expectations, and styling tiers.',
      uxStrategy: 'Developed an intuitive service navigation system categorizing treatments by discipline (Couture Hair, Color Artistry, Skin Therapies, and Rituals). Clear service timeframes, stylist specializations, and a prominent, persistent booking pathway streamline the guest journey from initial discovery to appointment request.',
      designDirection: 'Soft natural tones paired with high-contrast editorial serif headings, subtle border delineations, and atmospheric spatial photography that communicates hospitality, cleanliness, and mastery.',
      keyFeatures: [
        'Interactive treatment menu with duration, pricing tier, and specialist breakdowns',
        'Direct appointment inquiry workflow with preferred date and service selection',
        'Curated stylist portfolio showcasing signature editorial techniques',
        'Brand philosophy and organic ingredient ritual storytelling',
        'Location details, salon etiquette, and comprehensive visit preparation guides',
      ],
      responsiveDesign: 'Built desktop-first with a meticulous mobile-first touch architecture. High-priority actions—such as appointment booking, telephone inquiry, and location directions—are thumb-accessible, with optimized fluid typography and zero horizontal scroll on compact devices.',
      visualAndInteraction: 'Subtle hover states on service cards, lightweight fade-in animations on tab changes, and restrained motion curves that preserve the calming, spa-like atmosphere.',
      developmentApproach: 'Engineered using a modern React and TypeScript architecture styled with zero-runtime Tailwind CSS. Implemented semantic HTML5 tags for accessibility, lazy asset loading, and optimized bundle delivery for instant page loads on mobile networks.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons', 'Web API'],
      outcome: 'A modern, high-fashion salon website that accurately mirrors Atelier Aura’s physical luxury, providing prospective and returning clients with an inviting, intuitive service explorer and direct booking interface.',
      gallery: [],
    },
  },
  {
    id: 'coffeeian',
    slug: 'coffeeian',
    title: 'Coffeeian',
    category: 'Restaurant / Coffee & Kitchen',
    shortDescription: 'A warm, inviting digital kitchen and roastery experience showcasing artisanal brews, daytime dining menus, and table reservation workflows.',
    thumbnail: '',
    image: '',
    liveUrl: 'http://coffeeian.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 2,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Responsive Grid'],
    caseStudy: {
      overview: 'Coffeeian is an artisan coffee roastery and kitchen celebrating origin-sourced single-origin beans, craft brewing techniques, and seasonally inspired daytime dining. The web experience serves both daily patrons exploring menus and guests booking weekend table reservations.',
      businessType: 'Specialty Coffee Roastery, Artisan Bakery & Daytime Kitchen',
      challenge: 'Hospitality websites often force users to download awkward PDF menus or navigate confusing aggregators. Coffeeian needed a branded digital home where food menus are effortlessly readable on phones, bean origins are proudly highlighted, and reservations can be requested without friction.',
      designApproach: 'Engineered an earthy, welcoming visual system rooted in deep roasted hues, warm creams, and rich culinary imagery. Structured the layout to guide visitors naturally from roastery storytelling into interactive menu discovery and table booking.',
      uxStrategy: 'Created a tabbed, searchable menu architecture separating espresso bar drinks, pour-overs, brunch plates, and bakery goods. Clear dietary indicators (vegetarian, vegan, gluten-free) and flavor notes empower patrons to find their preferences quickly.',
      designDirection: 'Warm contemporary typography pairing, tactile background treatments, natural photography, and clean contrast standards that keep food and beverage descriptions appetizing and readable under varying ambient lighting.',
      keyFeatures: [
        'Organized digital menu with category filtering and dietary indicators',
        'Integrated table reservation inquiry system with party size and time options',
        'Interactive roastery guide detailing single-origin profiles and farm partners',
        'Store hours, real-time operating status, and interactive location map links',
        'Special events and private roastery tasting session booking forms',
      ],
      responsiveDesign: 'Optimized specifically for mobile customers on the move. Fast navigation shortcuts allow immediate access to location directions, operating hours, telephone dialing, and quick reservation submission.',
      visualAndInteraction: 'Smooth tab switching across menu categories, interactive card hovers, and clean modal dialogs built without layout shifts or intrusive popups.',
      developmentApproach: 'Built as a high-performance single-page web app using React and TypeScript. Configured lightweight SVG iconography, structured schema-ready markup for local business discovery, and responsive asset sizing.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
      outcome: 'A vibrant, dependable digital storefront that effectively captures the warmth of Coffeeian’s dining space while making menu discovery and dining reservations seamless for local guests.',
      gallery: [],
    },
  },
  {
    id: 'forty-nine',
    slug: 'forty-nine',
    title: 'Forty Nine',
    category: 'Accessories Brand',
    shortDescription: 'A sleek, minimalist digital catalog and brand flagship for contemporary accessories, highlighting material craftsmanship, curated collections, and modern product discovery.',
    thumbnail: '',
    image: '',
    liveUrl: 'https://forty-nine.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 3,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Catalog UI'],
    caseStudy: {
      overview: 'Forty Nine is an independent design studio creating modern leather goods, hardware, and everyday carry essentials. The website functions as an editorial brand catalog that emphasizes silhouette, texture, and lasting construction over fast-fashion clutter.',
      businessType: 'Contemporary Lifestyle Accessories & Handcrafted Leather Goods Brand',
      challenge: 'Accessories brands need to convey tactile qualities—leather temper, stitch density, and hardware weight—through digital screens. Generic storefront templates often bury craft details in overcrowded promotional banners. Forty Nine required an uncluttered, architectural showcase.',
      designApproach: 'Adopted a Scandinavian-inspired minimalism with generous white space, restrained typography, and sculptural image cropping. The user interface acts as a silent gallery frame, allowing the craftsmanship of each piece to stand out prominently.',
      uxStrategy: 'Designed a friction-free product exploration flow featuring quick collection filters (Carry, Small Goods, Belts, Hardware), multidimensional photography, detailed material specifications, and direct purchase inquiry pathways.',
      designDirection: 'Monochrome and graphite tones accented by crisp white, precise grid alignments, and high-resolution macro photography capturing leather grain, edge bevels, and hardware finishes.',
      keyFeatures: [
        'Curated product lookbook and accessories catalog with category filters',
        'Product detail modal with dimensions, leather provenance, and care instructions',
        'Artisan manufacturing narrative showcasing studio workshops and material sourcing',
        'Worldwide shipping reference guide and boutique stockist directory',
        'Direct customer concierge and bespoke custom-order inquiry form',
      ],
      responsiveDesign: 'Built to provide an app-like browsing experience on mobile devices, with seamless vertical scrolling, swipe-ready galleries, and thumb-friendly inquiry triggers.',
      visualAndInteraction: 'Deliberate micro-transitions, smooth image hover zooms, and refined button feedback designed to echo the precision of high-end industrial design.',
      developmentApproach: 'Developed in modular React with strict TypeScript typing. Optimized for rapid image rendering, minimal DOM complexity, and scalable data models facilitating straightforward future catalog updates.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
      outcome: 'A refined, editorial brand platform that positions Forty Nine alongside leading contemporary design studios, delivering an effortless browsing and product discovery experience across all devices.',
      gallery: [],
    },
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Discovery',
    description: 'Understand the business, goals, audience and requirements.',
  },
  {
    number: '02',
    title: 'Strategy',
    description: 'Plan the structure, functionality and user experience.',
  },
  {
    number: '03',
    title: 'Design',
    description: 'Create a premium and conversion-focused interface.',
  },
  {
    number: '04',
    title: 'Development',
    description: 'Build the frontend, backend and required integrations.',
  },
  {
    number: '05',
    title: 'Testing',
    description: 'Test responsiveness, functionality, performance and usability.',
  },
  {
    number: '06',
    title: 'Launch',
    description: 'Deploy the final product and provide launch support.',
  },
];

export const TECHNOLOGIES_CATEGORIES = [
  {
    category: 'Core & Languages',
    skills: ['HTML5', 'CSS3', 'JavaScript', 'Python', 'Java', 'JSON'],
  },
  {
    category: 'Frontend & UI',
    skills: ['React', 'Figma'],
  },
  {
    category: 'Backend & Data',
    skills: ['Node.js', 'Firebase', 'Supabase', 'Google Sheets'],
  },
  {
    category: 'CMS & Cloud Tooling',
    skills: ['WordPress', 'GitHub', 'Netlify', 'VS Code'],
  },
];

export const TECHNOLOGIES_LIST = [
  { name: 'HTML5', category: 'Frontend' },
  { name: 'CSS3', category: 'Styling' },
  { name: 'JavaScript', category: 'Language' },
  { name: 'React', category: 'Frontend' },
  { name: 'Node.js', category: 'Backend' },
  { name: 'Python', category: 'Backend' },
  { name: 'Java', category: 'Backend' },
  { name: 'JSON', category: 'Data' },
  { name: 'Figma', category: 'UI/UX' },
  { name: 'WordPress', category: 'CMS' },
  { name: 'VS Code', category: 'Tooling' },
  { name: 'GitHub', category: 'DevOps' },
  { name: 'Netlify', category: 'Cloud' },
  { name: 'Supabase', category: 'Database' },
  { name: 'Firebase', category: 'Database' },
  { name: 'Google Sheets', category: 'Integration' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: '$999',
    bestFor: 'Small businesses / simple online presence',
    popular: false,
    buttonText: 'Start Your Project',
    features: [
      'Professional custom website',
      'Up to 3 pages',
      'Premium responsive design',
      'Mobile / tablet / desktop optimization',
      'Contact / inquiry form',
      'WhatsApp or direct contact integration',
      'Google Maps integration',
      'Social media integration',
      'Basic SEO structure',
      'Basic performance optimization',
      'Deployment / launch support',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    price: '$1,999',
    bestFor: 'Established small businesses',
    popular: true,
    popularBadge: 'MOST POPULAR',
    buttonText: 'Build My Business Website',
    features: [
      'Everything in Starter',
      'Up to 5 pages',
      'Premium custom UI/UX',
      'Advanced animations and interactions',
      'Custom sections',
      'CMS / basic content management',
      'Database integration where required',
      'Advanced contact / inquiry system',
      'Analytics integration',
      'Enhanced SEO structure',
      'Performance optimization',
      'Business-focused conversion structure',
      'Custom integrations',
      'Deployment and launch support',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: '$3,499',
    bestFor: 'Businesses needing advanced features',
    popular: false,
    buttonText: 'Build My Solution',
    features: [
      'Everything in Business',
      'Advanced custom functionality',
      'Admin dashboard',
      'Authentication',
      'Database-driven features',
      'Dynamic content',
      'File / image management',
      'Advanced forms',
      'Custom business workflows',
      'Advanced integrations',
      'Advanced analytics',
      'Enhanced SEO',
      'Security best practices',
      'Performance optimization',
      'Post-launch support',
    ],
  },
  {
    id: 'advanced',
    name: 'Advanced',
    price: '$5,999+',
    bestFor: 'Full-stack / custom systems',
    popular: false,
    priceNote: 'Final pricing depends on project scope, complexity, integrations and technical requirements.',
    buttonText: 'Discuss Your Project',
    features: [
      'Everything in Premium',
      'Fully custom full-stack development',
      'Complex business logic',
      'Advanced dashboards',
      'Custom admin systems',
      'Booking / scheduling systems',
      'Payment integrations',
      'API integrations',
      'Advanced database architecture',
      'User authentication and roles',
      'Client portals',
      'Custom workflows',
      'Scalable architecture',
      'Third-party service integrations',
      'Custom automation',
      'Advanced performance optimization',
      'Extended support',
    ],
  },
];

export const PRICING_ADD_ONS: PricingAddOn[] = [
  { name: 'Extra Page', price: '$75–$150', description: 'Additional custom designed & coded page' },
  { name: 'Admin Dashboard', price: '$300–$700', description: 'Custom administrative interface for internal operations' },
  { name: 'Database Integration', price: '$200–$500', description: 'Structured database setup (Supabase, Firebase, SQL)' },
  { name: 'Authentication', price: '$200–$400', description: 'User registration, login, JWT & role access control' },
  { name: 'Booking System', price: '$300–$700', description: 'Interactive appointment scheduling & calendar sync' },
  { name: 'Payment Gateway', price: '$200–$500', description: 'Stripe, PayPal, or localized merchant checkout integration' },
  { name: 'WhatsApp Integration', price: '$75–$150', description: 'Direct one-tap inquiry chat and automated quick replies' },
  { name: 'Email Automation', price: '$100–$300', description: 'Transactional notification triggers & lead auto-responder' },
  { name: 'Advanced Animation', price: '$200–$500', description: 'Fluid micro-interactions, scroll physics & bespoke canvas effects' },
  { name: 'CMS Setup', price: '$300–$700', description: 'Headless or custom content management for self-updating' },
  { name: 'SEO Setup', price: '$150–$350', description: 'Technical schema markup, sitemaps, meta tags & indexing' },
  { name: 'Analytics Setup', price: '$75–$200', description: 'Google Analytics 4, conversion event tracking & dashboards' },
  { name: 'Maintenance & Support', price: '$150–$400/mo', description: 'Monthly security patches, speed audits & on-demand revisions' },
];

export const WHY_AMAAS_ITEMS: WhyUsReason[] = [
  {
    title: 'Custom Engineering, Zero Templates',
    description: 'Every digital solution is custom-coded from scratch to align with your unique business goals and workflows.',
    iconName: 'Sparkles',
  },
  {
    title: 'Business & Conversion-Focused',
    description: 'We prioritize high conversion rates, streamlined user journeys, and tangible business ROI over superficial decoration.',
    iconName: 'TrendingUp',
  },
  {
    title: 'Full-Stack Technical Depth',
    description: 'From interactive frontend experiences to complex databases, secure authentication, and APIs, everything works seamlessly.',
    iconName: 'Cpu',
  },
  {
    title: 'Ultra-Responsive & Fast',
    description: 'Optimized for sub-second load times and flawless presentation across mobile, tablet, and desktop displays globally.',
    iconName: 'Smartphone',
  },
  {
    title: 'Direct Developer Communication',
    description: 'Work directly with your technical specialist with zero account-manager layers, clear milestones, and rapid feedback.',
    iconName: 'MessageSquare',
  },
  {
    title: 'Scalable & Future-Proof',
    description: 'Built with clean, modern architectures that adapt effortlessly as your customer base and operations expand.',
    iconName: 'Rocket',
  },
];

export const TRUST_STATS = [
  { value: '100%', label: 'Custom Code & Logic' },
  { value: 'Full-Stack', label: 'Frontend + Backend' },
  { value: '< 1s', label: 'Load Time Benchmark' },
  { value: 'Global', label: 'US, UK, CA, EU & Beyond' },
];
