import { Project, ServiceItem, ProcessStep, PricingPlan, PricingAddOn, WhyUsReason } from './types';

export const SERVICES_DATA: ServiceItem[] = [
  {
    number: '01',
    title: 'Website Development',
    description: 'High-performance, responsive websites designed around business goals, seamless user journeys, and high conversion.',
    iconName: 'Globe',
    highlights: [
      'Modern responsive web architectures',
      'Ultra-fast load speeds & Core Web Vitals',
      'Mobile, tablet & desktop optimization',
      'Scalable frontend & backend engineering',
    ],
  },
  {
    number: '02',
    title: 'SEO',
    description: 'Technical, on-page and local SEO strategies designed to improve organic visibility, search rankings, and qualified traffic.',
    iconName: 'Search',
    highlights: [
      'Technical SEO audits & structured schema',
      'Search intent mapping & keyword research',
      'On-page content & metadata optimization',
      'Local search authority & indexing health',
    ],
  },
  {
    number: '03',
    title: 'AI Chatbots',
    description: 'AI-powered customer support and lead-generation assistants trained on your business data to engage visitors 24/7.',
    iconName: 'Bot',
    highlights: [
      '24/7 automated inquiry handling',
      'Lead capture & instant qualification',
      'Custom knowledge-base grounding',
      'Seamless CRM & email handoff',
    ],
  },
  {
    number: '04',
    title: 'AI Automation',
    description: 'Automate repetitive workflows, connect business tools, and reduce manual operational overhead across your organization.',
    iconName: 'Zap',
    highlights: [
      'Automated lead intake & client routing',
      'Multi-platform data synchronization',
      'Scheduled business workflows & alerts',
      'Elimination of manual repetitive tasks',
    ],
  },
  {
    number: '05',
    title: 'Google Ads',
    description: 'Performance-focused advertising campaigns designed to reach high-intent customers actively searching for your solutions.',
    iconName: 'Target',
    highlights: [
      'High-intent search keyword campaigns',
      'Performance Max & dynamic ad setup',
      'Negative keyword filtering & budget control',
      'End-to-end conversion tracking setup',
    ],
  },
  {
    number: '06',
    title: 'Meta Ads',
    description: 'Targeted advertising campaigns across Facebook and Instagram engineered to drive brand recall, inquiries, and sales.',
    iconName: 'Share2',
    highlights: [
      'Precision audience demographic targeting',
      'High-converting visual creative strategy',
      'Dynamic retargeting & funnel sequencing',
      'Continuous A/B testing & ROAS optimization',
    ],
  },
  {
    number: '07',
    title: 'Social Media Marketing',
    description: 'Content strategy, creative direction, and social media management designed to build authority and foster audience loyalty.',
    iconName: 'Megaphone',
    highlights: [
      'Editorial content calendars & strategy',
      'Visual asset design & storytelling',
      'Brand positioning & community growth',
      'Multi-channel performance reporting',
    ],
  },
  {
    number: '08',
    title: 'UI/UX & Creative Design',
    description: 'Modern interfaces, visual systems, and creative digital assets built around each brand to elevate perceived value.',
    iconName: 'Palette',
    highlights: [
      'Custom interface design & visual identity',
      'Conversion-focused user experience flows',
      'Interactive prototyping in modern tools',
      'Comprehensive design system guidelines',
    ],
  },
  {
    number: '09',
    title: 'Deployment & Technical Setup',
    description: 'Domain, hosting, deployment, and technical implementation ensuring resilient uptime, security, and peak performance.',
    iconName: 'Server',
    highlights: [
      'Custom domain DNS & SSL security setup',
      'Automated CI/CD build & deployment',
      'Edge CDN caching & global distribution',
      'Post-launch technical monitoring & support',
    ],
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'atelier-aura',
    slug: 'atelier-aura',
    title: 'Atelier Aura',
    category: 'Salon / Beauty & Wellness',
    badge: 'Demonstration Project',
    projectType: 'Luxury Salon & Wellness Digital Experience',
    servicesDemonstrated: ['Website Development', 'UI/UX & Creative Design', 'Deployment & Technical Setup'],
    shortDescription: 'A demonstration digital experience crafted for a modern salon and wellness retreat, featuring fluid typography, immersive service menus, and frictionless appointment booking.',
    thumbnail: '',
    image: '',
    liveUrl: 'https://atelier-aura.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 1,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
    caseStudy: {
      overview: 'Atelier Aura is a demonstration concept developed to showcase high-fashion digital styling, calm tactile ergonomics, and conversion-focused guest scheduling pathways for luxury beauty and aesthetic wellness sanctuaries.',
      businessType: 'Demonstration Concept: Boutique Salon & Wellness Sanctuary',
      challenge: 'Traditional beauty websites frequently suffer from cluttered third-party booking widgets, dated visual hierarchies, and uninspired layouts. The goal was to prove how refined typography and intuitive pathways elevate client trust.',
      designApproach: 'Formulated a serene architectural aesthetic centered around generous negative space, warm neutral undertones, and refined typography. The visual hierarchy invites unhurried exploration while clearly delineating treatment packages.',
      uxStrategy: 'Developed an intuitive service navigation system categorizing treatments by discipline (Couture Hair, Color Artistry, Skin Therapies, and Rituals). Clear service timeframes and stylist specializations streamline the inquiry journey.',
      designDirection: 'Soft natural tones paired with high-contrast editorial serif headings, subtle border delineations, and atmospheric spatial photography that communicates hospitality, cleanliness, and mastery.',
      keyFeatures: [
        'Interactive treatment menu with duration, tier breakdowns, and specialist notes',
        'Direct appointment inquiry workflow with preferred date and service selection',
        'Curated stylist portfolio showcasing signature editorial techniques',
        'Brand philosophy and organic ingredient ritual storytelling',
        'Location details, salon etiquette, and visit preparation guides',
      ],
      responsiveDesign: 'Built desktop-first with a meticulous mobile-first touch architecture. High-priority actions—such as appointment booking, telephone inquiry, and location directions—are thumb-accessible with zero horizontal scroll.',
      visualAndInteraction: 'Subtle hover states on service cards, lightweight fade-in animations on tab changes, and restrained motion curves that preserve the calming, spa-like atmosphere.',
      developmentApproach: 'Engineered using a modern React and TypeScript architecture styled with zero-runtime Tailwind CSS. Implemented semantic HTML5 tags for accessibility, lazy asset loading, and optimized bundle delivery.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons', 'Web API'],
      outcome: 'A modern, high-fashion salon website that demonstrates how luxury brand aesthetics and direct booking interfaces can work in perfect harmony.',
      gallery: [],
    },
  },
  {
    id: 'coffeeian',
    slug: 'coffeeian',
    title: 'Coffeeian',
    category: 'Restaurant / Coffee & Kitchen',
    badge: 'Demonstration Project',
    projectType: 'Artisanal Roastery & Kitchen Digital Hub',
    servicesDemonstrated: ['Website Development', 'UI/UX & Creative Design', 'Local Discovery UX'],
    shortDescription: 'A demonstration kitchen and roastery digital experience showcasing artisanal brews, daytime dining menus, and table reservation workflows.',
    thumbnail: '',
    image: '',
    liveUrl: 'http://coffeeian.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 2,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Responsive Grid'],
    caseStudy: {
      overview: 'Coffeeian is a demonstration digital platform exploring how modern food and hospitality businesses can replace clunky PDF menus with interactive, mobile-optimized ordering and reservation workflows.',
      businessType: 'Demonstration Concept: Specialty Coffee Roastery & Daytime Kitchen',
      challenge: 'Hospitality websites often force users to download awkward PDF menus or navigate confusing aggregators. Coffeeian was engineered to demonstrate effortless menu navigation on smartphones and quick table reservation requests.',
      designApproach: 'Engineered an earthy, welcoming visual system rooted in deep roasted hues, warm creams, and rich culinary imagery. Structured the layout to guide visitors naturally into interactive menu discovery.',
      uxStrategy: 'Created a tabbed, searchable menu architecture separating espresso bar drinks, pour-overs, brunch plates, and bakery goods. Clear dietary indicators empower patrons to find their preferences quickly.',
      designDirection: 'Warm contemporary typography pairing, tactile background treatments, natural photography, and clean contrast standards that keep food and beverage descriptions appetizing and readable.',
      keyFeatures: [
        'Organized digital menu with category filtering and dietary indicators',
        'Integrated table reservation inquiry system with party size and time options',
        'Interactive roastery guide detailing single-origin profiles and farm partners',
        'Store hours, real-time operating status, and interactive location map links',
        'Special events and private roastery tasting session booking forms',
      ],
      responsiveDesign: 'Optimized specifically for mobile customers on the move. Fast navigation shortcuts allow immediate access to location directions, operating hours, telephone dialing, and quick reservation submission.',
      visualAndInteraction: 'Smooth tab switching across menu categories, interactive card hovers, and clean modal dialogs built without layout shifts or intrusive popups.',
      developmentApproach: 'Built as a high-performance single-page web app using React and TypeScript. Configured lightweight SVG iconography, structured schema-ready markup for local business discovery, and responsive asset sizing.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
      outcome: 'A dependable digital storefront demonstrating how warmth, tactile culinary aesthetics, and frictionless reservation UX combine effectively.',
      gallery: [],
    },
  },
  {
    id: 'forty-nine',
    slug: 'forty-nine',
    title: 'Forty Nine',
    category: 'Accessories Brand',
    badge: 'Demonstration Project',
    projectType: 'Minimalist Accessories Catalog & Flagship',
    servicesDemonstrated: ['Website Development', 'UI/UX & Creative Design', 'Product Discovery UX'],
    shortDescription: 'A demonstration digital catalog and brand flagship for contemporary accessories, highlighting material craftsmanship, curated collections, and modern product discovery.',
    thumbnail: '',
    image: '',
    liveUrl: 'https://forty-nine.ai.studio/',
    year: '2026',
    featured: true,
    published: true,
    order: 3,
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Catalog UI'],
    caseStudy: {
      overview: 'Forty Nine is a demonstration brand platform created to showcase how luxury accessories and leather goods can communicate tactile material quality and silhouette elegance through minimal, high-fashion web design.',
      businessType: 'Demonstration Concept: Contemporary Lifestyle Accessories & Leather Goods',
      challenge: 'Accessories brands need to convey tactile qualities—leather temper, stitch density, and hardware weight—through digital screens. Forty Nine demonstrates an uncluttered, architectural showcase.',
      designApproach: 'Adopted a Scandinavian-inspired minimalism with generous white space, restrained typography, and sculptural image cropping. The user interface acts as a silent gallery frame.',
      uxStrategy: 'Designed a friction-free product exploration flow featuring quick collection filters (Carry, Small Goods, Belts, Hardware), multidimensional photography, and detailed material specifications.',
      designDirection: 'Monochrome and graphite tones accented by crisp white, precise grid alignments, and high-resolution macro photography capturing leather grain, edge bevels, and hardware finishes.',
      keyFeatures: [
        'Curated product lookbook and accessories catalog with category filters',
        'Product detail modal with dimensions, leather provenance, and care instructions',
        'Artisan manufacturing narrative showcasing studio workshops and material sourcing',
        'Worldwide shipping reference guide and boutique stockist directory',
        'Direct customer concierge and bespoke custom-order inquiry form',
      ],
      responsiveDesign: 'Built to provide an app-like browsing experience on mobile devices, with seamless vertical scrolling, swipe-ready galleries, and thumb-friendly inquiry triggers.',
      visualAndInteraction: 'Deliberate micro-transitions, smooth image hover zooms, and refined button feedback designed to echo the precision of high-end industrial design.',
      developmentApproach: 'Developed in modular React with strict TypeScript typing. Optimized for rapid image rendering, minimal DOM complexity, and scalable data models facilitating straightforward future catalog updates.',
      technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'Lucide Icons'],
      outcome: 'A refined brand platform demonstrating how minimal aesthetics and thoughtful product interactions build premium brand authority.',
      gallery: [],
    },
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Discover',
    description: 'Understand the business, audience and goals.',
  },
  {
    number: '02',
    title: 'Strategize',
    description: 'Create the right digital strategy.',
  },
  {
    number: '03',
    title: 'Build',
    description: 'Design, develop and integrate.',
  },
  {
    number: '04',
    title: 'Launch',
    description: 'Deploy and implement.',
  },
  {
    number: '05',
    title: 'Optimize',
    description: 'Measure, improve and scale.',
  },
  {
    number: '06',
    title: 'Monitor',
    description: 'Track performance, uptime and continuous health.',
  },
];

export const TECHNOLOGIES_CATEGORIES = [
  {
    category: 'Technology & Frontend',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'HTML5/CSS3', 'Next.js / Vite', 'JavaScript (ES6+)'],
  },
  {
    category: 'Backend, APIs & Cloud',
    skills: ['Node.js', 'Supabase', 'Firebase', 'RESTful APIs', 'SQL / PostgreSQL', 'Edge Functions'],
  },
  {
    category: 'AI & Automation',
    skills: ['AI Assistants / Chatbots', 'Workflow Automation', 'OpenAI & Claude APIs', 'Google Gemini', 'Webhook Pipelines'],
  },
  {
    category: 'Marketing & Analytics',
    skills: ['Google Ads', 'Meta Ads Manager', 'Technical SEO', 'Google Analytics 4', 'Search Console', 'Conversion APIs'],
  },
];

export const TECHNOLOGIES_LIST = [
  { name: 'React', category: 'Frontend' },
  { name: 'TypeScript', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Styling' },
  { name: 'Node.js', category: 'Backend' },
  { name: 'Supabase', category: 'Database' },
  { name: 'Firebase', category: 'Database' },
  { name: 'AI Chatbots', category: 'AI' },
  { name: 'AI Automation', category: 'AI' },
  { name: 'Google Ads', category: 'Marketing' },
  { name: 'Meta Ads', category: 'Marketing' },
  { name: 'Technical SEO', category: 'Marketing' },
  { name: 'Google Analytics 4', category: 'Analytics' },
  { name: 'Figma', category: 'UI/UX' },
  { name: 'GitHub', category: 'DevOps' },
  { name: 'Vite', category: 'Tooling' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'launch',
    name: 'Digital Launch Solution',
    price: 'Custom Quote',
    bestFor: 'Businesses launching or modernizing their core online presence',
    popular: false,
    buttonText: 'Request a Quote',
    priceNote: 'Tailored around your specific business goals, number of pages, and technical integrations.',
    features: [
      'High-performance custom website architecture',
      'Modern responsive UI/UX across mobile, tablet & desktop',
      'Clear conversion architecture & lead inquiry forms',
      'Technical SEO foundation & search console indexing',
      'Direct WhatsApp or communication channels integration',
      'Google Analytics 4 & basic conversion tracking',
      'Domain, SSL & high-speed deployment configuration',
    ],
  },
  {
    id: 'growth',
    name: 'Growth & Performance Solution',
    price: 'Custom Quote',
    bestFor: 'Growing businesses aiming to scale customer acquisition & leads',
    popular: true,
    popularBadge: 'MOST POPULAR',
    buttonText: 'Request a Quote',
    priceNote: 'Combines modern web engineering with targeted digital marketing campaigns.',
    features: [
      'Everything in Digital Launch Solution',
      'Targeted Google Ads & Meta Ads campaign strategy',
      'On-page & local SEO strategy for organic search visibility',
      'High-converting landing page optimization & A/B structures',
      'Custom animations, micro-interactions & visual branding',
      'AI chatbot integration for 24/7 lead capture & qualification',
      'Full-funnel analytics dashboard & conversion attribution',
      'Ongoing campaign iteration & performance review',
    ],
  },
  {
    id: 'ai-automation',
    name: 'AI & Workflow Automation',
    price: 'Custom Quote',
    bestFor: 'Organizations looking to automate repetitive operations & support',
    popular: false,
    buttonText: 'Request a Quote',
    priceNote: 'Custom-built automated systems and intelligent assistants for your business workflows.',
    features: [
      'Custom AI Chatbot trained on your business data & FAQs',
      '24/7 customer support & instant lead qualification workflows',
      'Automated operational pipelines & multi-tool integrations',
      'Direct handoff to CRM, email notifications, or WhatsApp',
      'Database integration (Supabase, Firebase, or SQL)',
      'Secure API endpoints & webhook management',
      'Staff onboarding guide & system monitoring',
    ],
  },
  {
    id: 'comprehensive',
    name: 'Comprehensive Agency Partner',
    price: 'Custom Quote',
    bestFor: 'Established brands needing an end-to-end tech + marketing agency partner',
    popular: false,
    buttonText: 'Request a Quote',
    priceNote: 'Complete digital ecosystem coverage across technology, AI, design, and multi-channel marketing.',
    features: [
      'Complete end-to-end full-stack digital development',
      'Multi-channel performance marketing (Google + Meta + SEO)',
      'Custom AI assistant + automated back-office workflows',
      'Custom client portals, administrative dashboards or CMS',
      'Continuous conversion rate optimization (CRO) & testing',
      'Creative asset production & social media content strategy',
      'Dedicated technical & marketing strategic oversight',
      'Priority SLA support & monthly milestone roadmaps',
    ],
  },
];

export const PRICING_ADD_ONS: PricingAddOn[] = [
  { name: 'AI Chatbot Assistant', price: 'Custom Scope', description: 'Interactive AI support assistant trained on your business data' },
  { name: 'Workflow Automation', price: 'Custom Scope', description: 'Automated CRM sync, lead routing, and repetitive task reduction' },
  { name: 'Google Ads Campaign Setup', price: 'Custom Scope', description: 'Search & Performance Max campaign build with conversion tracking' },
  { name: 'Meta Ads Campaign Setup', price: 'Custom Scope', description: 'Targeted Instagram & Facebook campaigns with creative direction' },
  { name: 'Technical SEO Optimization', price: 'Custom Scope', description: 'On-page structure, schema markup, and organic search indexing' },
  { name: 'Social Media Creative Suite', price: 'Custom Scope', description: 'Branded visual assets and strategic content frameworks' },
  { name: 'Custom Admin Dashboard', price: 'Custom Scope', description: 'Internal operational portal for content, leads, and management' },
  { name: 'Database & Auth Architecture', price: 'Custom Scope', description: 'Structured cloud database (Supabase, Firebase, SQL) with authentication' },
  { name: 'Speed & Core Web Vitals Audit', price: 'Custom Scope', description: 'Comprehensive performance tuning and asset optimization' },
  { name: 'Custom Domain & Cloud Setup', price: 'Custom Scope', description: 'Domain DNS routing, SSL certificates, and edge CDN distribution' },
  { name: 'Analytics & Event Tracking', price: 'Custom Scope', description: 'Google Analytics 4, Tag Manager, and conversion API attribution' },
  { name: 'Ongoing Technical Care', price: 'Custom Scope', description: 'Scheduled maintenance, security patches, and on-demand updates' },
];

export const WHY_AMAAS_ITEMS: WhyUsReason[] = [
  {
    title: 'Technology + Marketing Under One Roof',
    description: 'We bridge the gap between engineering and performance marketing so your digital presence both functions flawlessly and attracts customers.',
    iconName: 'Sparkles',
  },
  {
    title: 'Practical AI, Zero Hype',
    description: 'We deploy actionable AI chatbots and automation systems that save operational hours and capture qualified leads around the clock.',
    iconName: 'Cpu',
  },
  {
    title: 'Business & Conversion-Focused',
    description: 'Every interface, ad campaign, and SEO initiative is structured around measurable business ROI and customer acquisition.',
    iconName: 'TrendingUp',
  },
  {
    title: 'Custom Solutions, Zero Generic Templates',
    description: 'We build tailored digital solutions designed specifically around your operational goals, brand identity, and customer journey.',
    iconName: 'Rocket',
  },
  {
    title: 'Direct Strategic Communication',
    description: 'Work directly with specialized technical and marketing practitioners without layers of account-management friction.',
    iconName: 'MessageSquare',
  },
  {
    title: 'Global Delivery Standards',
    description: 'Clean, reliable, and compliant digital architectures delivered for businesses across North America, Europe, Australia, and worldwide.',
    iconName: 'Smartphone',
  },
];

export const TRUST_STATS = [
  { value: '4-in-1', label: 'Tech, Marketing, AI & Design' },
  { value: '100%', label: 'Custom Tailored Solutions' },
  { value: '24/7', label: 'AI Support & Lead Automation' },
  { value: 'Global', label: 'Clients Worldwide' },
];

export { SERVICE_PACKAGES_DATA } from './data/servicePackagesData';

